name: aurthokos
description: "অর্থকোষ (Arthokosh) - A premium personal finance manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management (MVVM)
  provider: ^6.1.2

  # Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # Notifications
  flutter_local_notifications:

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
