name: aurthokos
description: "অর্থকোষ (Orthokosh) - A premium personal finance manager"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management (MVVM)
  provider: ^6.1.2

  # Database
  sqflite: ^2.4.2
  path: ^1.9.1

  # Notifications
  flutter_local_notifications:

  # Auth / Session
  shared_preferences: ^2.3.4
  crypto: ^3.0.6

  # Utilities
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/Orthokosh.png"
  adaptive_icon_background: "#E91E8E"
  adaptive_icon_foreground: "images/Orthokosh.png"

flutter:
  uses-material-design: true
  assets:
    - images/Orthokosh.png
